### ISSUE TITLE
Issue: is `babel-preset-env` required in peerDependencies?

### ISSUE THREAD

**Issue by whichsteveyp** [tbranyen/hooks-theme-refs#1]
Just threw this into the HoC repo and saw some webpack compile errors:

```
ERROR in ./packages/card/~/hooks-theme-refs/dist/htr.js
Module build failed: Error: Couldn't find preset "env" relative to directory "/Users/srivas/netflix/house-of-cards/packages/card/node_modules/hooks-theme-refs"
    at /Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/srivas/HoC/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/srivas/HoC/node_modules/babel-loader/index.js:38:20)
    at Object.module.exports (/Users/srivas/HoC/node_modules/babel-loader/index.js:131:12)
 @ ./packages/card/src/card.js 29:22-49
Child html-webpack-plugin for "index.html":
         Asset    Size  Chunks       Chunk Names
    index.html  490 kB       0       
    chunk    {0} index.html 479 kB
        [0] ./~/html-webpack-plugin/lib/loader.js!./index.html 599 bytes {0}
        [1] ./~/lodash/lodash.js 478 kB {0}
        [2] (webpack)/buildin/module.js 259 bytes {0}
        [3] (webpack)/buildin/amd-options.js 43 bytes {0}
webpack: Failed to compile.
```

This seemed to resolved when I added `babel-preset-env` to my project. Can throw a quick PR if thats the case but wanted to check if this was an issue between repo configs first.

**Comment by tbranyen** [comment]
Going to close this as the current dist is parseable by uglifyjs (which is ES5 only).
